name: MinigameApp
options:
  bundleIdPrefix: com.sklabs
  deploymentTarget:
    iOS: "17.0"

targets:
  MinigameApp:
    type: application
    platform: iOS
    sources:
      - path: MinigameApp
        excludes:
          - Resources/Games/**
      - path: MinigameApp/Resources/Games
        type: folder
        buildPhase: resources
    info:
      path: MinigameApp/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sklabs.minigame
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: MinigameApp/Info.plist
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
        DEVELOPMENT_TEAM: "9XXV95QET4"
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
